-- =====================================================================
-- InventorySales_Queries.sql
-- Sample queries demonstrating a range of SQL techniques against the
-- InventorySales database.
-- =====================================================================
USE InventorySales;
-- ---------------------------------------------------------------------
-- Query 1: Basic SELECT + WHERE
-- Products running low on stock (fewer than 50 units on hand),
-- sorted so the most urgent restocks appear first.
-- ---------------------------------------------------------------------
SELECT ProductName, QuantityInStock, ReorderLevel
FROM Products
WHERE QuantityInStock < 50
ORDER BY QuantityInStock ASC;

-- ---------------------------------------------------------------------
-- Query 2: Multi-table JOIN
-- Every order with the customer who placed it and the employee who
-- processed it, joined across three tables.
-- ---------------------------------------------------------------------
SELECT
    o.OrderID,
    CONCAT(c.FirstName, ' ', c.LastName) AS Customer,
    CONCAT(e.FirstName, ' ', e.LastName) AS ProcessedBy,
    o.OrderDate,
    o.Status
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN Employees e ON o.EmployeeID = e.EmployeeID
ORDER BY o.OrderDate;

-- ---------------------------------------------------------------------
-- Query 3: Aggregate function (SUM) + GROUP BY
-- Total revenue generated by each product category, counting only
-- Completed orders (Pending/Cancelled orders haven't actually
-- generated revenue yet).
-- ---------------------------------------------------------------------
SELECT
    cat.CategoryName,
    SUM(od.Quantity * od.UnitPrice) AS TotalRevenue
FROM OrderDetails od
JOIN Orders o ON od.OrderID = o.OrderID
JOIN Products p ON od.ProductID = p.ProductID
JOIN Categories cat ON p.CategoryID = cat.CategoryID
WHERE o.Status = 'Completed'
GROUP BY cat.CategoryName
ORDER BY TotalRevenue DESC;

-- ---------------------------------------------------------------------
-- Query 4: Aggregate function (COUNT) + WHERE + HAVING
-- Customers with more than one non-cancelled order, i.e. repeat
-- customers worth highlighting for a loyalty program.
-- ---------------------------------------------------------------------
SELECT
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS Customer,
    COUNT(o.OrderID) AS OrderCount
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.Status <> 'Cancelled'
GROUP BY c.CustomerID, c.FirstName, c.LastName
HAVING COUNT(o.OrderID) > 1;

-- ---------------------------------------------------------------------
-- Query 5: Nested subquery + aggregate function (AVG)
-- Products priced above the average unit price across all products.
-- The subquery computes the average; the outer query filters against it.
-- ---------------------------------------------------------------------
SELECT ProductName, UnitPrice
FROM Products
WHERE UnitPrice > (SELECT AVG(UnitPrice) FROM Products)
ORDER BY UnitPrice DESC;

-- ---------------------------------------------------------------------
-- Query 6: JOIN + aggregate function (COUNT, SUM)
-- Number of Completed orders processed and total revenue generated by
-- each employee, ranked highest revenue first.
-- ---------------------------------------------------------------------
SELECT
    CONCAT(e.FirstName, ' ', e.LastName) AS Employee,
    COUNT(DISTINCT o.OrderID) AS OrdersProcessed,
    SUM(od.Quantity * od.UnitPrice) AS TotalRevenue
FROM Employees e
JOIN Orders o ON e.EmployeeID = o.EmployeeID
JOIN OrderDetails od ON o.OrderID = od.OrderID
WHERE o.Status = 'Completed'
GROUP BY e.EmployeeID, e.FirstName, e.LastName
ORDER BY TotalRevenue DESC;

-- =====================================================================
-- Reflection: How AI was used in this project
-- =====================================================================
-- 1.  Using AI as a coding assistant was extremely helpful for clarifying complex 
--     SQL clauses, specifically distinguishing when to filter row-level data using 
--     WHERE versus aggregated groups using HAVING.
-- 2. Claude generated the CREATE TABLE, INSERT, INDEX, and SELECT
--    scripts, but I directed a key design decision myself -- removing
--    AUTO_INCREMENT from every primary key -- and Claude updated all
--    dependent scripts to stay consistent with that change.
-- 3. Each script was actually executed against a live MySQL/MariaDB
--    instance as it was built, not just written, so I could confirm
--    the foreign keys, constraints, and queries genuinely work rather
--    than assuming the syntax was correct.
-- 4. I learned that MySQL/InnoDB automatically indexes foreign key
--    columns when a FOREIGN KEY constraint is created, which changed
--    how I approached the indexing script -- targeting columns that
--    needed indexes rather than duplicating ones that already existed.
-- 5. I reviewed the final queries and results myself to make sure they
--    reflected realistic business questions (low stock, repeat
--    customers, revenue by category) rather than just technically
--    valid SQL.